const keyToDisplay = {
    'availability': 'Availability',
    'time': 'Uploaded',
    'personal_info_ref': 'Ref',
    'personal_info_name': 'Name',
    'personal_info_type': 'Type',
    'personal_info_nationality': 'Nationality',
    'personal_info_date_of_birth': 'DOB',
    'personal_info_height': 'Height',
    'personal_info_weight': 'Weight',
    'personal_info_birth_state': 'Birth state',
    'personal_info_religion': 'Religion',
    'personal_info_ethnic_group': 'Ethnic Group',
    'education_formal_education': 'Education',
    'education_highest_education_level': 'Education level',
    'family_siblings': 'Siblings',
    'family_marital_status_status': 'Marital status',
    'family_marital_status_husband_occupation': "Husband's occupation",
    'family_children_number': 'No. of Children',
    'family_children_details': 'Children details',
    'salary_monthly_salary': 'Salary',
    'salary_rest_days_per_month_total': 'Rest days/Month',
    'salary_rest_days_per_month_compensate_fee': 'Compensation fee',
    'salary_reason': 'reason',
    'salary_placement_fee': 'Placement fee',
    'medical_history_allergies': 'allergies',
    'medical_history_past_and_existing_illnesses_mental_illness': 'mental illness',
    'medical_history_past_and_existing_illnesses_epilepsy': 'epilepsy',
    'medical_history_past_and_existing_illnesses_asthma': 'asthma',
    'medical_history_past_and_existing_illnesses_diabetes': 'diabetes',
    'medical_history_past_and_existing_illnesses_hypertension': 'hypertension',
    'medical_history_past_and_existing_illnesses_tuberculosis': 'tuberculosis',
    'medical_history_past_and_existing_illnesses_heart_disease': 'disease',
    'medical_history_past_and_existing_illnesses_malaria': 'malaria',
    'medical_history_past_and_existing_illnesses_operations': 'operations',
    'medical_history_physical_disabilities': 'Physical disabilities',
    'medical_history_dietary_restrictions': 'Dietary restrictions',
    'medical_history_food_handling_preferences': 'Dietary preferences',
    'skills_care_of_infants_children_willing': 'infant/children care (wiling)',
    'skills_care_of_infants_children_experience': 'infant/children care (experience)',
    'skills_care_of_elderly_willing': 'elderly care (willing)',
    'skills_care_of_elderly_experience': 'elderly care (experience)',
    'skills_care_of_disabled_willing': 'disabled care (willing)',
    'skills_care_of_disabled_experience': 'disabled care (experience)',
    'skills_general_housework_willing': 'general housework (willing)',
    'skills_general_housework_experience': 'general housework (experience)',
    'skills_cooking_willing': 'cooking (willing)',
    'skills_cooking_experience': 'cooking (experience)',
    'skills_cooking_cuisine': 'cuisine',
    'skills_spoken_language_abilities': 'spoken languages',
    'skills_other_skills': 'other skills',
    'employment_history_overseas_date': 'overseas employment date',
    'employment_history_overseas_country': 'country',
    'employment_history_overseas_employer': 'overseas employer',
    'employment_history_overseas_work_duties': 'Overseas work duties',
    'employment_history_singapore_previous_work_experience': 'Singapore Work experience',
    'employment_history_singapore_work_permit_no': 'Singapore',
    'employment_history_feedback_from_previous_employers': 'Feedback',
    'availability_for_interview_by_phone': 'Interview by phone',
    'availability_for_interview_by_videoconference': 'Interview by videoconference',
    'availability_for_interview_in_person': 'Interview in person',
    'remarks_preference_for_rest_day': 'Rest day(s)',
    'remarks_additional_remarks': 'remarks',
};

export default keyToDisplay;